version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    networks:
      - my_network
    ports:
      - "6379:6379"

  ai-chat-bot:
    image: edu473/ai-chat-bot:latest
    container_name: ai-chat-bot
    command: /bin/sh -c "pnpm db:migrate && pnpm start"
    ports:
      - "3001:3000"
    networks:
      - my_network
    env_file:
      - .env.local
    depends_on:
      - postgres
      - redis
      - edusoft

  edusoft:
    image: edu473/edusoft:ai-latest
    container_name: edusoft
    command: ["/bin/sh", "-c", "sleep 1d"]
    networks:
      my_network:
        ipv4_address: 172.20.0.10

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
